In [5]:
import numpy as np


In [10]:
 a = np.arange(6)
 a2 = a[np.newaxis, :]
 a2.shape

(1, 6)

In [11]:
for i in range(3):
  x=i
x

2

In [12]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [14]:
'''
 you can also use 
np.linspace()
 to create an array with values that are spaced linearly in a speci ed
interval:
'''
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr.sort()
print(arr)

[1 2 3 4 5 6 7 8]


In [21]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
'''argsort, which is an indirect sort along a speci ed axis,
lexsort, which is an indirect stable sort on multiple keys,
searchsorted, which will nd elements in a sorted array, and
partition, which is a partial sort.'''
