#Numpy Ecercise

#Numpy has 256 function

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [5]:
my_List = [1, 2, 3, 4, 5]
type(my_List)

list

In [8]:
arr= np.array(my_List)
type(arr)

numpy.ndarray

In [9]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(11) # Starting from 0 to 10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(10, 20) # Starting from 10 to 19

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(10, 20, 3) # Starting from 10 to 19 with a step of 3. The output will be [10, 13, 16, 19]

array([10, 13, 16, 19])

In [15]:
np.zeros(5) # This will create an array of zeros with a length of 5. The output will be [0., 0., 0., 0., 0.]

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros(5, dtype=int) # This will create an array of zeros with a length of 5 and the data type will be integer. The output will be [0, 0, 0, 0, 0]

array([0, 0, 0, 0, 0])

In [17]:
np.zeros((2, 3)) # This will create a 2D array of zeros with 2 rows and 3 columns. The output will be [[0., 0., 0.], [0., 0., 0.]]

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros((2, 3), dtype=int) # This will create a 2D array of zeros with 2 rows and 3 columns. The output will be [[0, 0, 0], [0, 0, 0]]

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
np.ones(10) # This will create an array of ones with a length of 10. The output will be [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]    

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones((3,3), dtype = int)     # This will create a 2D array of ones with 3 rows and 3 columns. The output will be [[1, 1, 1], [1, 1, 1], [1, 1, 1]]

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
np.twos(3)  

AttributeError: module 'numpy' has no attribute 'twos'

In [22]:
rand(4)

NameError: name 'rand' is not defined

In [23]:
random.rand(4)

NameError: name 'random' is not defined

In [24]:
np.random.rand(0) # This will create an empty array. The output will be []

array([], dtype=float64)

In [26]:
np.random.rand(3)#

array([0.10700515, 0.88008262, 0.13099658])

In [27]:
np.random.rand(2,2) 

array([[0.16561237, 0.46685156],
       [0.05707162, 0.75117855]])

In [28]:
np.random.randint(3) 

1

In [29]:
np.random.randint(3) 

1

In [30]:
np.random.randint(10, 15)

11