# Numpy Crash Course

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
import sys 
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

## Creating Arrays

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [52]:
type(my_list)

list

In [6]:
arr = np.array(my_list) 
arr


array([0, 1, 2, 3, 4, 5])

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [57]:
np. # we learn important function 

SyntaxError: invalid syntax (1655120754.py, line 1)

In [10]:
np.arange(15) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(3.0)  

array([0., 1., 2.])

In [12]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int64)

In [16]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [18]:
np.arange(-20,-10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [19]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int64)

In [20]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [21]:
np.arange(10,10) 

array([], dtype=int64)

In [22]:
np.arange()

TypeError: arange() requires stop to be specified.

In [23]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [24]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [25]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [26]:
np.zeros(3) # parameter  tunning 

array([0., 0., 0.])

In [27]:
np.zeros(5, dtype=int) # hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [28]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [29]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [30]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [31]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [81]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [33]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [36]:
n

(6, 7)

In [37]:
n1

(6, 8)

In [38]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [39]:
np.ones(3)

array([1., 1., 1.])

In [40]:
np.ones (3)

array([1., 1., 1.])

In [41]:
np.ones((3, 1))

array([[1.],
       [1.],
       [1.]])

In [42]:
np.ones (2,3)

TypeError: Cannot interpret '3' as a data type

In [43]:
np.ones ((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [45]:
np.ones(4)

array([1., 1., 1., 1.])

In [46]:
n

(6, 7)

In [93]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [47]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [95]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [48]:
np.twos((2,3)) 

AttributeError: module 'numpy' has no attribute 'twos'

In [49]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [50]:
np.ones(2)

array([1., 1.])

In [51]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [101]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [102]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [36]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

In [53]:
range(5)

range(0, 5)

In [54]:
r = range(5)
r

range(0, 5)

In [55]:
for i in r:
    print(i)

0
1
2
3
4


In [56]:
list(range(5))

[0, 1, 2, 3, 4]

In [57]:
range(1,10)

range(1, 10)

In [58]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
list(range(1,10,3))

[1, 4, 7]

In [60]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [61]:
rand(3,2)

NameError: name 'rand' is not defined

In [112]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [62]:
np.random.rand(5)

array([0.80060534, 0.96978918, 0.10316667, 0.66742119, 0.5711017 ])

In [119]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [126]:
np.random.rand(2,4)

array([[0.73794061, 0.85933955, 0.05963442, 0.24872975],
       [0.49333625, 0.65918332, 0.40605833, 0.90842629]])

In [134]:
np.random.randint(2,4)

3

In [139]:
np.random.randint(2,20) # 2nd argument is exlusive 

4

In [49]:
np.random.randint(0,2) 

array([0, 0], dtype=int32)

In [42]:
np.random.randint(10,20,5)

array([15, 13, 17, 13, 16], dtype=int32)

In [39]:
np.random.randint(1,6,4)

array([3, 2, 2, 3], dtype=int32)

In [40]:
np.random.rand(3)

array([0.27665427, 0.3132414 , 0.09129694])

In [41]:
np.random.randint(1)  

0

In [149]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [150]:
np.random.randint(-30,20,10) 

array([-26, -27, -30,  -9,  -3,  -9, -26,   2,   1, -12])

In [ ]:
np.random.randint(20,30,10) 

In [ ]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

In [50]:
np.random.randint(10,21,3)

array([19, 13, 13], dtype=int32)

In [51]:
np.random.randint(1,12,10)

array([ 2,  4,  9,  4,  4,  4,  4,  6, 10,  9], dtype=int32)

In [52]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

array([[18, 39, 39, 30, 17, 18, 37, 14, 20, 36],
       [37, 28, 10, 35, 15, 21, 36, 34, 36, 17],
       [23, 30, 36, 28, 10, 14, 28, 33, 16, 26],
       [38, 34, 14, 37, 21, 26, 22, 17, 12, 14],
       [38, 16, 20, 33, 20, 33, 38, 11, 19, 34],
       [19, 28, 27, 25, 20, 21, 12, 25, 31, 12],
       [14, 25, 10, 13, 37, 34, 26, 16, 20, 32],
       [15, 33, 21, 31, 27, 13, 34, 17, 30, 36],
       [22, 23, 11, 31, 16, 13, 31, 15, 36, 13],
       [23, 28, 10, 21, 20, 31, 34, 35, 37, 28]], dtype=int32)

In [153]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

array([[77,  3, 76, 53, 28, 39, 81, 69, 90, 15, 28, 78],
       [43,  7, 29, 42, 82,  2, 18, 39, 32, 96, 26, 91],
       [54, 93, 31, 76, 39, 75, 60, 67, 12, 81, 78, 22],
       [10, 94, 23, 13, 57, 36, 74, 33, 35, 75, 11, 77],
       [86, 95, 61, 70, 14, 89,  4,  1, 74,  9, 20, 99],
       [20, 68, 66, 44, 56, 54, 40, 55, 10, 14, 55, 64],
       [35, 77, 79,  1, 96, 92, 77, 66, 55, 53,  4, 77],
       [64, 79, 12, 35, 20, 44, 51, 11, 54,  1, 99, 82],
       [ 2, 87, 50, 10, 19,  6, 65, 24, 20, 52,  6, 86],
       [85, 26, 49, 80, 54, 52, 49, 44, 91,  1, 16,  2],
       [44, 30, 21, 95, 33,  6, 65, 99, 67, 72, 81, 20],
       [19, 37, 12, 85, 69, 48, 61, 31, 35, 39, 10, 23]])

In [159]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [64]:
b = np.random.randint(10,20,(5,4))
b

array([[11, 13, 14, 17],
       [18, 11, 16, 19],
       [18, 16, 17, 18],
       [14, 10, 13, 17],
       [14, 12, 12, 17]], dtype=int32)

In [65]:
type(b)

numpy.ndarray

In [60]:
b

array([[14, 12, 18, 10],
       [15, 14, 16, 12],
       [17, 19, 11, 14],
       [16, 15, 17, 10],
       [18, 10, 14, 15]], dtype=int32)

In [66]:
b[:] 

array([[11, 13, 14, 17],
       [18, 11, 16, 19],
       [18, 16, 17, 18],
       [14, 10, 13, 17],
       [14, 12, 12, 17]], dtype=int32)

In [67]:
b[1:3]# row slicing

array([[18, 11, 16, 19],
       [18, 16, 17, 18]], dtype=int32)

In [68]:
b

array([[11, 13, 14, 17],
       [18, 11, 16, 19],
       [18, 16, 17, 18],
       [14, 10, 13, 17],
       [14, 12, 12, 17]], dtype=int32)

In [70]:
b[1,3]# column slicing

np.int32(19)

In [71]:
b

array([[11, 13, 14, 17],
       [18, 11, 16, 19],
       [18, 16, 17, 18],
       [14, 10, 13, 17],
       [14, 12, 12, 17]], dtype=int32)

In [72]:
b[1,3]

np.int32(19)

In [73]:
b[1,-2]

np.int32(16)

In [74]:
b

array([[11, 13, 14, 17],
       [18, 11, 16, 19],
       [18, 16, 17, 18],
       [14, 10, 13, 17],
       [14, 12, 12, 17]], dtype=int32)

In [75]:
b[2:3]

array([[18, 16, 17, 18]], dtype=int32)

In [76]:
b

array([[11, 13, 14, 17],
       [18, 11, 16, 19],
       [18, 16, 17, 18],
       [14, 10, 13, 17],
       [14, 12, 12, 17]], dtype=int32)

In [77]:
b[0:-2] 

array([[11, 13, 14, 17],
       [18, 11, 16, 19],
       [18, 16, 17, 18]], dtype=int32)

In [77]:
b

array([[14, 12, 18, 10],
       [15, 14, 16, 12],
       [17, 19, 11, 14],
       [16, 15, 17, 10],
       [18, 10, 14, 15]], dtype=int32)

In [78]:
b[0,2] 

np.int32(18)

In [79]:
b

array([[14, 12, 18, 10],
       [15, 14, 16, 12],
       [17, 19, 11, 14],
       [16, 15, 17, 10],
       [18, 10, 14, 15]], dtype=int32)

In [78]:
b[-5,-4] 

np.int32(11)

In [79]:
b

array([[11, 13, 14, 17],
       [18, 11, 16, 19],
       [18, 16, 17, 18],
       [14, 10, 13, 17],
       [14, 12, 12, 17]], dtype=int32)

In [80]:
b[-4,2] 

np.int32(16)

In [81]:
np.random.randint(10,20,(4,4))

array([[19, 11, 18, 12],
       [11, 16, 12, 15],
       [12, 17, 16, 15],
       [15, 11, 17, 15]], dtype=int32)

In [82]:
b 

array([[11, 13, 14, 17],
       [18, 11, 16, 19],
       [18, 16, 17, 18],
       [14, 10, 13, 17],
       [14, 12, 12, 17]], dtype=int32)

In [83]:
b[-4,-2]

np.int32(16)

In [84]:
b

array([[11, 13, 14, 17],
       [18, 11, 16, 19],
       [18, 16, 17, 18],
       [14, 10, 13, 17],
       [14, 12, 12, 17]], dtype=int32)

In [85]:
b[-4:2] 

array([[18, 11, 16, 19]], dtype=int32)

In [86]:
b[:]

array([[11, 13, 14, 17],
       [18, 11, 16, 19],
       [18, 16, 17, 18],
       [14, 10, 13, 17],
       [14, 12, 12, 17]], dtype=int32)

## Operations

In [87]:
a = np.random.randint(10,20,10)
a

array([16, 11, 15, 18, 14, 19, 19, 10, 12, 16], dtype=int32)

In [88]:
id(a)

2439101406864

In [89]:
arr

array([0, 1, 2, 3, 4, 5])

In [90]:
arr2 = np.random.randint(0,100,(10,10))

In [91]:
arr2

array([[90, 58, 68,  1, 76, 69, 41, 72, 71, 55],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3],
       [ 8, 60, 49, 24, 56, 19, 96,  4, 59, 58],
       [58, 54, 17,  3, 51, 50, 29, 96, 73, 50],
       [85, 79, 80, 13, 66, 46, 49, 94, 46, 26]], dtype=int32)

In [92]:
arr2

array([[90, 58, 68,  1, 76, 69, 41, 72, 71, 55],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3],
       [ 8, 60, 49, 24, 56, 19, 96,  4, 59, 58],
       [58, 54, 17,  3, 51, 50, 29, 96, 73, 50],
       [85, 79, 80, 13, 66, 46, 49, 94, 46, 26]], dtype=int32)

In [93]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [94]:
arr=np.random.randint(0,10,(2,5))
arr

array([[6, 7, 0, 0, 1],
       [6, 4, 0, 3, 3]], dtype=int32)

In [95]:
arr[:4] 

array([[6, 7, 0, 0, 1],
       [6, 4, 0, 3, 3]], dtype=int32)

In [96]:
arr2[:]

array([[90, 58, 68,  1, 76, 69, 41, 72, 71, 55],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3],
       [ 8, 60, 49, 24, 56, 19, 96,  4, 59, 58],
       [58, 54, 17,  3, 51, 50, 29, 96, 73, 50],
       [85, 79, 80, 13, 66, 46, 49, 94, 46, 26]], dtype=int32)

In [97]:
arr2[0:5] 

array([[90, 58, 68,  1, 76, 69, 41, 72, 71, 55],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50]], dtype=int32)

In [98]:
arr2

array([[90, 58, 68,  1, 76, 69, 41, 72, 71, 55],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3],
       [ 8, 60, 49, 24, 56, 19, 96,  4, 59, 58],
       [58, 54, 17,  3, 51, 50, 29, 96, 73, 50],
       [85, 79, 80, 13, 66, 46, 49, 94, 46, 26]], dtype=int32)

In [99]:
arr2[1,4] 

np.int32(88)

In [100]:
arr2

array([[90, 58, 68,  1, 76, 69, 41, 72, 71, 55],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3],
       [ 8, 60, 49, 24, 56, 19, 96,  4, 59, 58],
       [58, 54, 17,  3, 51, 50, 29, 96, 73, 50],
       [85, 79, 80, 13, 66, 46, 49, 94, 46, 26]], dtype=int32)

In [101]:
arr2[-5,5] 

np.int32(32)

In [102]:
arr2[-5,-5] 

np.int32(32)

In [103]:
arr2

array([[90, 58, 68,  1, 76, 69, 41, 72, 71, 55],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3],
       [ 8, 60, 49, 24, 56, 19, 96,  4, 59, 58],
       [58, 54, 17,  3, 51, 50, 29, 96, 73, 50],
       [85, 79, 80, 13, 66, 46, 49, 94, 46, 26]], dtype=int32)

In [104]:
arr2[-5,-5]

np.int32(32)

In [105]:
arr2

array([[90, 58, 68,  1, 76, 69, 41, 72, 71, 55],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3],
       [ 8, 60, 49, 24, 56, 19, 96,  4, 59, 58],
       [58, 54, 17,  3, 51, 50, 29, 96, 73, 50],
       [85, 79, 80, 13, 66, 46, 49, 94, 46, 26]], dtype=int32)

In [106]:
arr2[-1,-2]

np.int32(46)

In [107]:
arr2

array([[90, 58, 68,  1, 76, 69, 41, 72, 71, 55],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3],
       [ 8, 60, 49, 24, 56, 19, 96,  4, 59, 58],
       [58, 54, 17,  3, 51, 50, 29, 96, 73, 50],
       [85, 79, 80, 13, 66, 46, 49, 94, 46, 26]], dtype=int32)

In [108]:
arr2[::-1]

array([[85, 79, 80, 13, 66, 46, 49, 94, 46, 26],
       [58, 54, 17,  3, 51, 50, 29, 96, 73, 50],
       [ 8, 60, 49, 24, 56, 19, 96,  4, 59, 58],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [90, 58, 68,  1, 76, 69, 41, 72, 71, 55]], dtype=int32)

In [109]:
arr2

array([[90, 58, 68,  1, 76, 69, 41, 72, 71, 55],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3],
       [ 8, 60, 49, 24, 56, 19, 96,  4, 59, 58],
       [58, 54, 17,  3, 51, 50, 29, 96, 73, 50],
       [85, 79, 80, 13, 66, 46, 49, 94, 46, 26]], dtype=int32)

In [110]:
arr2[::-2] 

array([[85, 79, 80, 13, 66, 46, 49, 94, 46, 26],
       [ 8, 60, 49, 24, 56, 19, 96,  4, 59, 58],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13]], dtype=int32)

In [111]:
arr2

array([[90, 58, 68,  1, 76, 69, 41, 72, 71, 55],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3],
       [ 8, 60, 49, 24, 56, 19, 96,  4, 59, 58],
       [58, 54, 17,  3, 51, 50, 29, 96, 73, 50],
       [85, 79, 80, 13, 66, 46, 49, 94, 46, 26]], dtype=int32)

In [112]:
arr2[::-3]

array([[85, 79, 80, 13, 66, 46, 49, 94, 46, 26],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [90, 58, 68,  1, 76, 69, 41, 72, 71, 55]], dtype=int32)

In [113]:
arr2

array([[90, 58, 68,  1, 76, 69, 41, 72, 71, 55],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3],
       [ 8, 60, 49, 24, 56, 19, 96,  4, 59, 58],
       [58, 54, 17,  3, 51, 50, 29, 96, 73, 50],
       [85, 79, 80, 13, 66, 46, 49, 94, 46, 26]], dtype=int32)

In [114]:
arr2[:-3] 

array([[90, 58, 68,  1, 76, 69, 41, 72, 71, 55],
       [19, 97, 24, 63, 88, 42, 45, 91, 91, 13],
       [64, 33, 64, 73, 47, 49, 16, 82,  1, 92],
       [ 3, 49, 46, 51, 12, 18, 80, 79, 56, 23],
       [ 8,  9, 25, 66, 33, 39, 27, 34, 14, 50],
       [16, 29, 88, 49, 71, 32, 53, 87, 13, 40],
       [43, 24,  7, 23, 29, 17, 44, 86, 85,  3]], dtype=int32)

In [115]:
arr

array([[6, 7, 0, 0, 1],
       [6, 4, 0, 3, 3]], dtype=int32)

In [116]:
arr.max() 

np.int32(7)

In [117]:
arr.min()

np.int32(0)

In [118]:
arr

array([[6, 7, 0, 0, 1],
       [6, 4, 0, 3, 3]], dtype=int32)

In [119]:
arr.mean()

np.float64(3.0)

In [120]:
arr

array([[6, 7, 0, 0, 1],
       [6, 4, 0, 3, 3]], dtype=int32)

In [123]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [124]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

# Without work on import* can you please find the median, mode)

In [148]:
arr

array([[7, 9, 5, 3, 3],
       [6, 4, 5, 7, 9]], dtype=int32)

In [150]:
arr.reshape(2,5)  

array([[7, 9, 5, 3, 3],
       [6, 4, 5, 7, 9]], dtype=int32)

In [151]:
arr.reshape(5,2)  

array([[7, 9],
       [5, 3],
       [3, 6],
       [4, 5],
       [7, 9]], dtype=int32)

In [153]:
arr.reshape(1,10)

array([[7, 9, 5, 3, 3, 6, 4, 5, 7, 9]], dtype=int32)

In [128]:
arr

array([[6, 7, 0, 0, 1],
       [6, 4, 0, 3, 3]], dtype=int32)

In [129]:
arr.reshape(2,5) 
arr

array([[6, 7, 0, 0, 1],
       [6, 4, 0, 3, 3]], dtype=int32)

In [130]:
arr

array([[6, 7, 0, 0, 1],
       [6, 4, 0, 3, 3]], dtype=int32)

In [131]:
''''C' → go across rows ➡️
'F' → go down columns ⬇️
'A' → “do whatever the array prefers”
'''
arr.reshape(2,5,order='A') 

array([[6, 7, 0, 0, 1],
       [6, 4, 0, 3, 3]], dtype=int32)

In [132]:
arr.reshape(2,5,order='F') # print element with fortran 

array([[6, 7, 0, 0, 1],
       [6, 4, 0, 3, 3]], dtype=int32)

In [135]:
arr.reshape(2,5,order='C') # A almost give you c type output 

array([[6, 7, 0, 0, 1],
       [6, 4, 0, 3, 3]], dtype=int32)

In [160]:
arr

array([[7, 9, 5, 3, 3],
       [6, 4, 5, 7, 9]], dtype=int32)

In [161]:
arr.reshape(2,3)

ValueError: cannot reshape array of size 10 into shape (2,3)

In [162]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 10 into shape (1,4)

In [163]:
arr.reshape(1,6)  

ValueError: cannot reshape array of size 10 into shape (1,6)

In [164]:
arr.reshape(6,1)  

ValueError: cannot reshape array of size 10 into shape (6,1)

In [165]:
arr.reshape(2,6) 

ValueError: cannot reshape array of size 10 into shape (2,6)

In [166]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 10 into shape (3,3)

In [167]:
arr

array([[7, 9, 5, 3, 3],
       [6, 4, 5, 7, 9]], dtype=int32)

In [168]:
arr.reshape(3,2)  

ValueError: cannot reshape array of size 10 into shape (3,2)

## Indexing

In [136]:
mat = np.arange(0,100).reshape(10,10) 

In [137]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [170]:
row = 4
col = 5

In [231]:
col

5

In [232]:
row

4

In [171]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [172]:
mat[row,col] 

np.int64(45)

In [173]:
mat[4,5] 

np.int64(45)

In [235]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [174]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [175]:
col = 6

In [176]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [177]:
mat[6] # befault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [178]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [179]:
# With Slices
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [180]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [181]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [182]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [183]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [184]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [185]:
mat[:col] 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [186]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
row


In [187]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [188]:
mat[:row]  

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [189]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [190]:
mat[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [191]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [139]:
mat[:,8] 

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [ ]:
mat

In [193]:
mat[:,-1] 

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [ ]:
mat

In [ ]:
row

In [ ]:
col

In [194]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [ ]:
mat

In [195]:
mat[1,4]

np.int64(14)

In [ ]:
mat

In [196]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [198]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [197]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [ ]:
mat

In [ ]:
mat[0]

In [199]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [ ]:
mat

In [200]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [201]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
mat

In [202]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [ ]:
mat

In [203]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat

In [140]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [141]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [142]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat

In [ ]:
mat[4:]

In [ ]:
mat

In [205]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
mat

In [206]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [208]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [207]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [ ]:
mat

In [ ]:
mat[::-3]

In [ ]:
mat

In [209]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
mat

In [143]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [211]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [246]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [ ]:
mat

In [212]:
mat[0,1]

np.int64(1)

In [213]:
mat[1,6]

np.int64(16)

In [214]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [215]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [216]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [144]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [217]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
mat[0:1]

In [ ]:
mat

In [218]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [219]:
mat[3,5]

np.int64(35)

In [266]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[1:2,2:4] # 1:2 --> only row part /// 2:4 -- it indicates only column parts, mat[m,n-1:m1,n-1:n1]

array([[12, 13]])

In [247]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [221]:
mat[2:3,2:3] 

array([[22]])

In [249]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [222]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [250]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [ ]:
mat

In [ ]:
mat[2:3,4:5]

## Masking

In [223]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [225]:
id(mat)

1804855165072

In [226]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [227]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [228]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [229]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [230]:
mat[mat==50] 

array([50])

In [231]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [232]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
mat

In [233]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
mat

In [234]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
a3 = mat[mat<=50] 
a3

In [235]:
a4 = mat[mat==50]
a4

array([50])

# python program to generat otp 

In [236]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 1310


In [237]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [238]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [239]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x000001A439854100>


In [240]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
